name: Manual - Migrate database

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get runner IP
        shell: pwsh
        run: curl https://jsonip.com/

      - name: Wait 60 seconds - YOUR ACTION NEEDED!
        shell: pwsh
        run: |
          echo "Please update the SQL server firewall rules to allow connections from this IP."
          echo "60s remaining"
          Start-Sleep -s 30
          echo "30s remaining"
          Start-Sleep -s 20
          echo "10s remaining"
          Start-Sleep -s 5
          echo "5s remaining"
          Start-Sleep -s 5
          echo "0s remaining"
      
      - name: Apply migration
        shell: pwsh
        env:
          SqlConnectionString: ${{ secrets.SQL_CONNECTION_STRING }}
        run: |
          pushd './Api'
          dotnet tool install --global dotnet-ef
          dotnet ef migrations bundle
          ./efbundle.exe --connection "${{ secrets.SQL_CONNECTION_STRING }}"
          popd
